github: [mikemcquaid, hzoo]
patreon: mikekavouras
open_collective: mikekavouras
ko_fi: mikekavouras
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: mariogrip
issuehunt: sindresorhus
otechie: nuxt
custom: https://mikekavouras.com/donate
